#!/bin/csh -f

#set basedir_version = v6.2.8 # working for tier-1 and tier-2 
set basedir_version = v7.7.0 # currently working for tier-1 only

set node = `uname -n`
module purge
if (( $node =~ tier2* ) || ( $node =~ r* )) then
    echo "Loading modules for Tier-2..."
    set basedir_path = /staging/leuven/stg_00024/GEOSldas_libraries
    module unuse /apps/leuven/skylake/2018a/modules/all
    module unuse /apps/leuven/cascadelake/2018a/modules/all
    module unuse /apps/leuven/cascadelake/2019b/modules/all
    module use /apps/leuven/skylake/2019b/modules/all
    module load foss flex Bison CMake Autotools texinfo gomkl Python/2.7.16-GCCcore8.3.0
else if ( $node =~ *dodrio* ) then 
    echo "Loading modules for Hortense Tier-1..."
    set basedir_path = /dodrio/scratch/projects/2022_200/project_input/rsda/ldas/GEOSldas_libraries
    module --force purge
    module load cluster/dodrio/cpu_milan_rhel9
    module load foss/2023a
    module load flex/2.6.4-GCCcore-12.3.0
    module load Bison/3.8.2-GCCcore-12.3.0
    module load CMake/3.26.3-GCCcore-12.3.0
    module load Autotools/20220317-GCCcore-12.3.0
    module load libtirpc/1.3.3-GCCcore-12.3.0
    module load makeinfo/7.0.3-GCCcore-12.3.0
    module load Python/2.7.18-GCCcore-12.3.0
    module load imkl/2023.1.0
else 
    echo "Platform not found ... exit"
    exit 1
endif

if (( $basedir_version =~ v6.2.8 )) then
    setenv BASEDIR $basedir_path/ESMA-Baselibs-$basedir_version/src/Linux
    setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$BASEDIR/lib
else 
    setenv BASEDIR $basedir_path/ESMA-Baselibs-$basedir_version/Linux
    setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$BASEDIR/lib
endif
