#!/bin/csh -f

#set basedir_version = v6.2.8 # working for tier-1 and tier-2 
set basedir_version = v6.2.13 # currently working for tier-1 only

set node = `uname -n`
module purge
if (( $node =~ tier2* ) || ( $node =~ r* )) then
    echo "Loading modules for Tier-2..."
    set basedir_path = /staging/leuven/stg_00024/GEOSldas_libraries
    module unuse /apps/leuven/skylake/2018a/modules/all
    module unuse /apps/leuven/cascadelake/2018a/modules/all
    module unuse /apps/leuven/cascadelake/2019b/modules/all
    module use /apps/leuven/skylake/2019b/modules/all
    module load foss flex Bison CMake Autotools texinfo gomkl Python/2.7.16-GCCcore8.3.0
else if ( $node =~ *dodrio* ) then 
    echo "Loading modules for Hortense Tier-1..."
    set basedir_path = /dodrio/scratch/projects/2022_200/project_input/rsda/ldas/GEOSldas_libraries
    module --force purge
    module load cluster/dodrio/cpu_rome
    module load foss/2021b 
    module load flex/2.6.4-GCCcore-11.2.0 
    module load Bison/3.7.6-GCCcore-11.2.0 
    module load CMake/3.22.1-GCCcore-11.2.0 
    module load Autotools/20210726-GCCcore-11.2.0 
    module load texinfo/6.8-GCCcore-11.2.0 
    module load libtirpc/1.3.2-GCCcore-11.2.0
    module load Python/2.7.18-GCCcore-11.2.0
    module load imkl/2022.1.0
else 
    echo "Platform not found ... exit"
    exit 1
endif

if (( $basedir_version =~ v6.2.8 )) then
    setenv BASEDIR $basedir_path/ESMA-Baselibs-$basedir_version/src/Linux
    setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$BASEDIR/lib
else 
    setenv BASEDIR $basedir_path/ESMA-Baselibs-$basedir_version/Linux
    setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$BASEDIR/lib
endif
